AlgorithmAnalysis: Helper Class Reference
Helper Class Reference
Static methods that generates and copies random integer arrays.
#include <Helper.h>
Static Public Member Functions
static void createRandomArray (int V[], int arrayLength, int maxInteger)
Creates a random integer array between 0 and MaxInteger.
static void copyArray (int V[], int W[], int n)
Copies an array contents into another array with the same length.
static bool checkArrayEquality (int V[], int W[], int n)
Checks equality between two given arrays (both arrays have same content in same order)
static bool checkIsOrdered (int V[], int n)
Checks if an array is ordered.
static void printArrayContents (int V[], int n)
Prints array content on console.
static void executePlotCommand ()
Executes the shell script to generate the image files.
Static Private Member Functions
static bool checkSameLength (int V[], int W[])
Detailed Description
Static methods that generates and copies random integer arrays.
Author:
Sergio Revilla
Definition at line 19 of file Helper.h.
Member Function Documentation
bool Helper::checkArrayEquality (int V[], int W[], int n) [static]
Checks equality between two given arrays (both arrays have same content in same order)
Parameters:
V the original array
W the other array
n the array's length
Definition at line 30 of file Helper.cpp.
References checkSameLength().
bool Helper::checkIsOrdered (int V[], int n) [static]
Checks if an array is ordered.
Parameters:
V the array
n the array's length
Definition at line 50 of file Helper.cpp.
bool Helper::checkSameLength (int V[], int W[]) [static, private]
Definition at line 23 of file Helper.cpp.
Referenced by checkArrayEquality().
void Helper::copyArray (int V[], int W[], int n) [static]
Copies an array contents into another array with the same length.
Parameters:
V the original array
W the cloned array
n the array's length
Definition at line 17 of file Helper.cpp.
Referenced by Generator::generateBubbleSortDataFile(), Generator::generateInsertionSortDataFile(), Generator::generateMergeSortDataFile(), Generator::generateQuickSortDataFile(), Generator::generateSelectionSortDataFile(), and Testing::makeFourCopies().
void Helper::createRandomArray (int V[], int arrayLength, int maxInteger) [static]
Creates a random integer array between 0 and MaxInteger.
Parameters:
V an array already set to a length of arrayLength
arrayLength the array's length
maxInteger the maximum integer to generate
Definition at line 10 of file Helper.cpp.
Referenced by Testing::generateArray().
void Helper::executePlotCommand () [static]
Executes the shell script to generate the image files.
Definition at line 79 of file Helper.cpp.
void Helper::printArrayContents (int V[], int n) [static]
Prints array content on console.
Parameters:
V the array
n the array's length
Definition at line 66 of file Helper.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
include/Helper.h
src/Helper.cpp