AlgorithmAnalysis: Testing Class Reference
Testing Class Reference
Static methods that generates data from user input values.
#include <Testing.h>
Static Public Member Functions
static void generateArray (int V[], int n, int maxInt)
Generates an array with n random integers betwwen 0 and maxInt.
static void makeFourCopies (int V[], int first[], int second[], int third[], int fourth[], int n)
Makes four copies of a given array.
Detailed Description
Static methods that generates data from user input values.
Author:
Sergio Revilla
Definition at line 14 of file Testing.h.
Member Function Documentation
void Testing::generateArray (int V[], int n, int maxInt) [static]
Generates an array with n random integers betwwen 0 and maxInt.
Parameters:
V the container array with a size of n
n The array length
maxInt maximum integer to generate arraty to
Definition at line 17 of file Testing.cpp.
References Helper::createRandomArray().
Referenced by main().
void Testing::makeFourCopies (int V[], int first[], int second[], int third[], int fourth[], int n) [static]
Makes four copies of a given array.
Parameters:
V the original array
n the array length
Definition at line 10 of file Testing.cpp.
References Helper::copyArray().
The documentation for this class was generated from the following files:
include/Testing.h
src/Testing.cpp